version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: switch-tube-downloader
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

archives:
  - format: "zip"
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

changelog:
  disable: true
