name: PR Labeler

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize

jobs:
  labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/labeler.yaml"
          sync-labels: true
